#!/bin/bash

function download() {
    url=$1
    dest=$2

    response=$(curl -X GET ${url} -o -)
    format=$(echo ${response} | jq -r .format)
    if [ "${format}" = "base64" ] ; then
        echo ${response} | jq -j .content | base64 -d > $dest
    elif [ "${format}" = "text" ] ; then
        echo ${response} | jq -j .content > $dest
    else
        echo "Format ${format} of file ${dest} not supported"
        echo ${response} | jq -j .content > $dest
    fi
}

notebook_created="no"

function get_notebook() {
    ## Creates a new notebook if needed. Sets flag to delete if
    ## notebook was re-created.
    apiurl=$1
    sessionid=$2
    serviceid=$3
    svcinfo=`curl --silent -X GET "${apiurl}/${serviceid}" -H  "accept: application/json"`
    if [ $(echo ${svcinfo} | jq -j .sessionId) = "${sessionid}" ] ; then
        return ## NOTEBOOK_URL unchanged.
    fi
    
    svcinfo=`curl --silent -X POST "${apiurl}" -H  "accept: application/json" \
                  -H  "Content-Type: application/json" -d "{\"sessionId\":\"${sessionid}\"}"`
    notebook_created="yes"
    
    svcurl=`echo ${svcinfo} | jq -j .serviceURL`
    if [ "${svcurl}" = "null" ] ; then
        echo "Session ${sessionid} no longer exists. Cannot download data."
        exit 1
    fi

    SERVICE_ID=`echo ${svcinfo} | jq -j .id`
    echo "Wait for service ${SERVICE_ID} to be re-created at ${svcurl}."
    while ! curl --silent -IL -X GET ${svcurl} | grep "200 OK" ; do
        sleep 5
    done
    NOTEBOOK_URL=${svcurl}
}

function delete_notebook() {
    apiurl=$1
    if [ "${notebook_created}" = "yes" ] ; then
        curl -X DELETE "${apiurl}/${SERVICE_ID}" -H  "accept: */*"
    fi
}

function download_working_dir_data() {
    if [ ! -e download_filelist.dat ] ; then
        echo "Nothing to download from working dir."
        return
    fi
    apiurl=$1
    for file in `cat download_filelist.dat` ; do
        download ${apiurl}/${file} ${HOME}/${file}
    done
}

conda install -y -c conda-forge curl jq || exit 1


# =======================================================
# Everything below here is generated by the snapshot job:
# =======================================================
NOTEBOOK_URL=http://epos-ics-d.brgm-rec.fr/swirrl/jupyter/e4c7d40e-1aa5-4d6a-9160-f570bc8e03de
SERVICE_ID=e4c7d40e-1aa5-4d6a-9160-f570bc8e03de
get_notebook http://swirrl-api/swirrl-api/v1.0/notebook 951cb598-9c19-41e5-a3f2-b720beb64d7e e4c7d40e-1aa5-4d6a-9160-f570bc8e03de
mkdir -p ~/data/staginghistory/stage.00007
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00007/filenamejc3.mseed ~/data/staginghistory/stage.00007/filenamejc3.mseed
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00007/filename1.xml ~/data/staginghistory/stage.00007/filename1.xml
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00007/filenamejc.xml ~/data/staginghistory/stage.00007/filenamejc.xml
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00007/filename2.mseed ~/data/staginghistory/stage.00007/filename2.mseed
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00007/filename3.mseed ~/data/staginghistory/stage.00007/filename3.mseed
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00007/filenamejc.mseed ~/data/staginghistory/stage.00007/filenamejc.mseed
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00007/filenamejc2.mseed ~/data/staginghistory/stage.00007/filenamejc2.mseed
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00007/swirrl_fileinfo.json ~/data/staginghistory/stage.00007/swirrl_fileinfo.json
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00007/filename3.seed ~/data/staginghistory/stage.00007/filename3.seed
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00007/filenamejc1.xml ~/data/staginghistory/stage.00007/filenamejc1.xml
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00007/filename2.seed ~/data/staginghistory/stage.00007/filename2.seed
mkdir -p ~/data/staginghistory/stage.00006
ln ~/data/staginghistory/stage.00007//filename1.xml ~/data/staginghistory/stage.00006/filename1.xml
ln ~/data/staginghistory/stage.00007//filenamejc3.mseed ~/data/staginghistory/stage.00006/filenamejc3.mseed
ln ~/data/staginghistory/stage.00007//filenamejc1.xml ~/data/staginghistory/stage.00006/filenamejc1.xml
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00006/swirrl_fileinfo.json ~/data/staginghistory/stage.00006/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00007//filenamejc.xml ~/data/staginghistory/stage.00006/filenamejc.xml
ln ~/data/staginghistory/stage.00007//filename3.mseed ~/data/staginghistory/stage.00006/filename3.mseed
ln ~/data/staginghistory/stage.00007//filename2.mseed ~/data/staginghistory/stage.00006/filename2.mseed
ln ~/data/staginghistory/stage.00007//filename3.seed ~/data/staginghistory/stage.00006/filename3.seed
ln ~/data/staginghistory/stage.00007//filenamejc.mseed ~/data/staginghistory/stage.00006/filenamejc.mseed
ln ~/data/staginghistory/stage.00007//filenamejc2.mseed ~/data/staginghistory/stage.00006/filenamejc2.mseed
ln ~/data/staginghistory/stage.00007//filename2.seed ~/data/staginghistory/stage.00006/filename2.seed
mkdir -p ~/data/staginghistory/stage.00005
ln ~/data/staginghistory/stage.00006//filenamejc.xml ~/data/staginghistory/stage.00005/filenamejc.xml
ln ~/data/staginghistory/stage.00006//filename2.mseed ~/data/staginghistory/stage.00005/filename2.mseed
ln ~/data/staginghistory/stage.00006//filename3.seed ~/data/staginghistory/stage.00005/filename3.seed
ln ~/data/staginghistory/stage.00006//filename2.seed ~/data/staginghistory/stage.00005/filename2.seed
ln ~/data/staginghistory/stage.00006//filenamejc.mseed ~/data/staginghistory/stage.00005/filenamejc.mseed
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00005/swirrl_fileinfo.json ~/data/staginghistory/stage.00005/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00006//filename3.mseed ~/data/staginghistory/stage.00005/filename3.mseed
ln ~/data/staginghistory/stage.00006//filename1.xml ~/data/staginghistory/stage.00005/filename1.xml
mkdir -p ~/data/staginghistory/stage.00004
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00004/swirrl_fileinfo.json ~/data/staginghistory/stage.00004/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00005//filename2.mseed ~/data/staginghistory/stage.00004/filename2.mseed
ln ~/data/staginghistory/stage.00005//filename2.seed ~/data/staginghistory/stage.00004/filename2.seed
ln ~/data/staginghistory/stage.00005//filename1.xml ~/data/staginghistory/stage.00004/filename1.xml
ln ~/data/staginghistory/stage.00005//filename3.seed ~/data/staginghistory/stage.00004/filename3.seed
ln ~/data/staginghistory/stage.00005//filename3.mseed ~/data/staginghistory/stage.00004/filename3.mseed
mkdir -p ~/data/staginghistory/stage.00003
ln ~/data/staginghistory/stage.00004//filename2.seed ~/data/staginghistory/stage.00003/filename2.seed
ln ~/data/staginghistory/stage.00004//filename2.mseed ~/data/staginghistory/stage.00003/filename2.mseed
ln ~/data/staginghistory/stage.00004//filename3.seed ~/data/staginghistory/stage.00003/filename3.seed
ln ~/data/staginghistory/stage.00004//filename1.xml ~/data/staginghistory/stage.00003/filename1.xml
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/swirrl_fileinfo.json ~/data/staginghistory/stage.00003/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00004//filename3.mseed ~/data/staginghistory/stage.00003/filename3.mseed
mkdir -p ~/data/staginghistory/stage.00002
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00002/swirrl_fileinfo.json ~/data/staginghistory/stage.00002/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00003//filename1.xml ~/data/staginghistory/stage.00002/filename1.xml
ln ~/data/staginghistory/stage.00003//filename2.seed ~/data/staginghistory/stage.00002/filename2.seed
ln ~/data/staginghistory/stage.00003//filename3.seed ~/data/staginghistory/stage.00002/filename3.seed
mkdir -p ~/data/staginghistory/stage.00001
ln ~/data/staginghistory/stage.00002//filename3.seed ~/data/staginghistory/stage.00001/filename3.seed
ln ~/data/staginghistory/stage.00002//filename1.xml ~/data/staginghistory/stage.00001/filename1.xml
ln ~/data/staginghistory/stage.00002//filename2.seed ~/data/staginghistory/stage.00001/filename2.seed
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/swirrl_fileinfo.json ~/data/staginghistory/stage.00001/swirrl_fileinfo.json
ln -s ~/data/staginghistory/stage.00007 ~/data/latest
download_working_dir_data ${NOTEBOOK_URL}/api/contents
delete_notebook http://swirrl-api/swirrl-api/v1.0/notebook
